name: E2E

on:
  pull_request:
  push:

jobs:
  nixos-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-target:
          - television-action-modes
          - flake-television-action-modes

    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Run ${{ matrix.test-target }} test
        run: nix-build ./tests -A ${{ matrix.test-target }} --show-trace
